version: "3.2"
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    environment:
      - VIRTUAL_HOST=portainer-taller.duckdns.org
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=portainer-taller.duckdns.org
      - LETSENCRYPT_EMAIL=danielsantar98@gmail.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainerdata:/data
    networks:
      - vendecrispetasproxy

networks:
  vendecrispetasproxy:
    external: true

volumes:
  portainerdata:
    driver: local
