version: "3.2"

services:
  taller:
    image: taller:1.0.0
    build:
      context: ./final-web
      dockerfile: Dockerfile
    command: gunicorn app.main:app -w 1 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:80
    env_file:
      - .taller.env
    networks:
      - vendecrispetas
      - vendecrispetasproxy
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure

networks:
  vendecrispetas:
    external: true
  vendecrispetasproxy:
    external: true
